// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewArticle struct {
	Content string `json:"content"`
	UserID  int    `json:"userId"`
	Tags    []int  `json:"tags"`
}

type NewComment struct {
	Content   string `json:"content"`
	UserID    int    `json:"userId"`
	ArticleID int    `json:"articleId"`
}

type NewTag struct {
	Name string `json:"name"`
}

type NewUser struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
